In [54]:
import librosa
import librosa.display
import IPython.display as ipd
import matplotlib.pyplot as plt
import tensorflow as tf


import numpy as np
from ipywidgets import *

In [55]:
FRAME_SIZE = 255
HOP_SIZE = 128

In [56]:
speech_sr = 16000

train_ds, test_ds = tf.keras.utils.audio_dataset_from_directory(
                            directory="./Prototype/mini_speech_commands",
                            batch_size=None,
                            validation_split=0.2,
                            seed=1,
                            output_sequence_length=16000,
                            subset='both'
                        )

Found 8000 files belonging to 8 classes.
Using 6400 files for training.
Using 1600 files for validation.


# Speech

In [57]:
for speech_wav, label in train_ds.take(1):
    pass
    
speech_wav = speech_wav.numpy()
speech_wav = np.reshape(speech_wav, newshape=(-1,))
speech_wav

2024-05-14 21:59:21.360210: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


array([ 3.0517578e-05, -3.0517578e-05,  6.1035156e-05, ...,
       -3.0517578e-05,  3.0517578e-05, -6.1035156e-05], dtype=float32)

In [58]:
ipd.Audio(speech_wav, rate=speech_sr)

# Idel noise

In [59]:
idel_wav_file_path = "./LESSI noise/Idel.wav"
idel_wav, sr = librosa.load(idel_wav_file_path)

idel_wav = librosa.resample(y=idel_wav, orig_sr=sr, target_sr=speech_sr)
idel_wav = idel_wav[:len(speech_wav)]
idel_wav

array([ 0.00387343,  0.00678216,  0.00428579, ..., -0.00348529,
       -0.00423514, -0.00388131], dtype=float32)

In [60]:
ipd.Audio(idel_wav, rate=speech_sr)

# Speech + idel noise

In [61]:
for alpha in np.arange(1, 0, -0.1):
    print(f"alpha = {alpha:.2f}")
    superimposed = alpha * speech_wav + (1 - alpha) * idel_wav
    ipd.display(ipd.Audio(superimposed, rate=speech_sr))

alpha = 1.00


alpha = 0.90


alpha = 0.80


alpha = 0.70


alpha = 0.60


alpha = 0.50


alpha = 0.40


alpha = 0.30


alpha = 0.20


alpha = 0.10


In [62]:
for alpha in np.arange(0.1, 0, -0.01):
    print(f"alpha = {alpha:.2f}")
    superimposed = alpha * speech_wav + (1 - alpha) * idel_wav
    ipd.display(ipd.Audio(superimposed, rate=speech_sr))

alpha = 0.10


alpha = 0.09


alpha = 0.08


alpha = 0.07


alpha = 0.06


alpha = 0.05


alpha = 0.04


alpha = 0.03


alpha = 0.02


alpha = 0.01


# Walk noise

In [63]:
walk_wav_file_path = "./LESSI noise/Walk.wav"
walk_wav, sr = librosa.load(walk_wav_file_path)

walk_wav = walk_wav[50000:250000]
walk_wav = librosa.resample(y=walk_wav, orig_sr=sr, target_sr=speech_sr)
walk_wav = walk_wav[:len(speech_wav)]
walk_wav

array([ 0.30093446,  0.2823282 , -0.00275133, ..., -0.04082428,
       -0.02659082, -0.04581523], dtype=float32)

In [64]:
ipd.Audio(walk_wav, rate=speech_sr)

# Speech + idel noise

In [65]:
for alpha in np.arange(1, 0, -0.1):
    print(f"alpha = {alpha:.2f}")
    superimposed = alpha * speech_wav + (1 - alpha) * walk_wav
    ipd.display(ipd.Audio(superimposed, rate=speech_sr))

alpha = 1.00


alpha = 0.90


alpha = 0.80


alpha = 0.70


alpha = 0.60


alpha = 0.50


alpha = 0.40


alpha = 0.30


alpha = 0.20


alpha = 0.10
